# 23.Swift访问权限、异常

## 模块和源文件

- 模块——独立的单元构建和发布单位，可以理解为一个特定功能的代码集合，并且可以使用 Swift 的 `import` 关键字导入到另一个模块。
- **注意：**模块不是目录，更不是文件夹，而是某个功能的集合，比如`UIKit`、`第三方框架`等
- 源文件是一个模块中的单个 Swift 源代码文件。

## 访问权限

- `open`  和 `public` :允许实体被定义模块中的任意源文件访问，也可以被另一模块的源文件通过导入该定义模块来访问。在指定框架的公共接口时，通常使用 open 或 public。

  public修饰的class只允许外部模块调用，但是不允许继承。 而open修饰的class既允许其他模块调用，也允许被子类继承。

  public修饰的成员只允许其他模块调用，但不能被覆盖(override)。而open修饰的成员既允许被其他模块调用，也允许成员被覆盖。

- `internal` :允许实体被定义模块中的任意源文件访问，但不能被该模块之外的任何源文件访问。通常在定义应用程序或是框架的内部结构时使用。(**默认级别**)

- `fileprivate`:将实体的使用限制于当前定义源文件中。

- `private` : 将实体的使用限制于封闭声明中，比fileprivate更严格。

  open > public > internal > fileprivate > private

**注意**：

- 访问权限可以修饰 类、方法、属性等。
- 在 Swift 4 中，private 的属性的作用域扩大到了 extension 中，也就是说在 extension 中访问属性可以是 fileprivate 或者 private 修饰的。

## 异常

- 只要我们在编程，就一定要面对错误处理的问题。
- Swift在设计的时候就尽可能让我们知道错误发生的地方和原因，然后正确的处理错误
- 如何描述一个错误？
  - 在Swift里，任何一个遵从`Error` protocol的类型，都可以用于描述错误。
  - `Error`是一个空的protocol，它唯一的功能，就是告诉Swift编译器，某个类型用来表示一个错误。
  - 通常，我们使用一个enum来定义各种错误的可能性

## 异常处理

- 假如我们想要读取一个文件中的内容，在读取的时候可能出错，比如当我们调用方法获取结果为nil时，并不能确定到底发生了什么错误

```swift
func readFileContent(filePath : String) -> String? {
    // 1.filePath为""
    if filePath == "" {
        return nil
    }

    // 2.filepath有值,但是没有对应的文件
    if filePath != "/User/Desktop/123.plist" {
        return nil
    }

    // 3.取出其中的内容
    return "123"
}

readFileContent(filePath: "abc")
```

- 使用异常对上述方法进行改进

```swift
// 1.定义异常
enum FileReadError : Error {
    case FileISNull
    case FileNotFound
}

// 2.改进方法,让方法抛出异常
func readFileContent(filePath : String) throws -> String {
    // 1.filePath为""
    if filePath == "" {        
        throw FileReadError.FileISNull
    }    
    // 2.filepath有值,但是没有对应的文件
    if filePath != "/User/Desktop/123.plist" {        
        throw FileReadError.FileNotFound
    }    
    // 3.取出其中的内容
    return "123"
}
```

- 处理异常有三种方式

1. `do try catch`方式,需要手动处理异常（建议使用）

```swift
do {
    let result = try readFileContent(filePath: "abc")
} catch {
    //有一个隐含参数 error
    print(error)
}
```

1. `try?`方式,不处理异常,如果出现了异常,则返回一个nil.没有异常,则返回对应的值

```swift
// 最终返回结果为一个可选类型
let result = try? readFileContent(filePath: "abc")
```

1. `try!`方式,告诉系统该方法没有异常,一旦如果出现了异常,则程序会直接崩溃

```swift
let result = try! readFileContent(filePath: "abc")
```

- ```swift
  defer
  ```

  关键字

  - 修饰函数内任一段代码，调用时机：在函数中的其余代码都执行完毕，函数即将结束前
  - 可以用它在异常中进行扫尾工作，比如关闭IO流，释放资源等

```swift
do{
    //虽然写在前面 但后执行
    defer {
        print("执行defer")
    }
   print("Hello")
   try readFileContent(filePath: "")
   print("World")
}

catch{    
    print(error)
}
//打印信息
//Hello
//执行defer
//FileISNull
```